// LEXER (TOKENS)

const STRING_TYPE = "SCRIPTURE";
const NUMBER_TYPE = "RIM"; 
const IDENTIFIER_TYPE = "IDENTIFIER";

const LEFT_PARENTHESIS = "L_PARENTH";
const RIGHT_PARENTHESIS = "R_PARENTH";
const SEMICOLON = "END";

// PARSER (ASTS)

const DISPLAY_FUNCTION_AST = "F_Sceawian"

// PARSER (DISPLAY FUNCTIONS)

const DISPLAY_FUNCTION_DISPLAY = "sceawian"

export default {
    STRING_TYPE, NUMBER_TYPE, IDENTIFIER_TYPE,
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, SEMICOLON,
    DISPLAY_FUNCTION_AST, DISPLAY_FUNCTION_DISPLAY
}
